[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-10_x"]

[phases.install]
cmds = [
  "npm ci --legacy-peer-deps"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "node .output/server/index.mjs"

[variables]
NODE_ENV = "production"
